version: "3"

services:
  # main bolna service (web/api on 5001)
  bolna-app:
    build:
      context: .
      dockerfile: dockerfiles/bolna_server.Dockerfile
    image: bolna-app:latest
    ports:
      - "5001:5001"
    depends_on:
      - redis
    env_file:
      - ../.env
    volumes:
      - ../agent_data:/app/agent_data
      # Eğer AWS kimlik bilgileri kullanmayacaksanız aşağıdaki iki satırı EKLEMEYİN.
      # Aksi halde hostta bu klasörler yoksa mount hatası alırsınız.
      # - ${HOME}/.aws/credentials:/root/.aws/credentials:ro
      # - ${HOME}/.aws/config:/root/.aws/config:ro

  # redis service used as a persistent storage
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
